### PR TITLE
Fix dev environment on Windows

### LINKED ISSUE #289: Fix dev environment on Windows
### What's up?

As [reported](https://github.com/react-cosmos/react-cosmos/issues/288#issuecomment-279400489) by @reinei it seems like the build scripts don't work on Windows environments.

### Mkay, tell me more...

It might have something to do with how `PACKAGE` is passed via [environment var](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/scripts/build.js#L26-L28) to [npm script](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/package.json#L13). 

@ovidiubute any ideas or do you have a Windows machine to test on?

### PR DESCRIPTION
**Pull request by RadValentin**
Fixes #289 and #288

### CODE REVIEW

**Comment by RadValentin** [comment]
@skidding @ovidiubute Can you guys take a look? Windows users should be OK now, the only thing that I couldn't get to work were the tests for the Flatris example as they [reference an external `node_modules`](https://github.com/react-cosmos/react-cosmos/blob/master/examples/flatris/package.json#L26) but that should be fixed with #301.

File: packages/react-cosmos-config/src/index.js [hunk 1]
```diff
@@ -1,11 +1,12 @@
 import path from 'path';
+import slash from 'slash';
 import resolveFrom from 'resolve-from';
 import importModule from 'react-cosmos-utils/lib/import-module';
 
 const resolveUserPath = (userPath, rootPath) =>
-  path.isAbsolute(userPath) ? userPath : (
+  slash(path.isAbsolute(userPath) ? userPath : (
```
Comment (ovidiubute) [inline packages/react-cosmos-config/src/index.js]: You don't need to use `slash` for the entire branch. `path.join` already uses the platform specific separator. In this particular case you could call `slash` just for the `userPath`. [Source](https://nodejs.org/api/path.html#path_path_join_paths)

File: packages/react-cosmos-voyager/src/__tests__/index.js [hunk 2]
```diff
@@ -1,8 +1,9 @@
 import path from 'path';
+import slash from 'slash';
 import traverse from 'traverse';
 import getFilePaths from '../index';
 
-const resolvePath = relPath => path.join(__dirname, '../use-cases', relPath);
+const resolvePath = relPath => slash(path.join(__dirname, '../use-cases', relPath));
```
Comment (ovidiubute) [inline packages/react-cosmos-voyager/src/__tests__/index.js]: `relPath` seems to be the only possible offender, so call `slash` only on that.

File: packages/react-cosmos-config/src/index.js (hunk 1 above)
Comment (skidding) [inline packages/react-cosmos-config/src/index.js]: > path.join already uses the platform specific separator

@ovidiubute yes, but it doesn't normalize the existing slashes from the concatenated paths. Am I right?

Comment (ovidiubute) [inline packages/react-cosmos-config/src/index.js]: Yeah I see what you mean, `path.join` is called with `userPath` which could have any combination of forward/back slashes. So `slash` is indeed required. 👍

**Comment by skidding** [comment]
@RadValentin I agree with https://github.com/react-cosmos/react-cosmos/pull/303#discussion_r104289808, otherwise looks good! Also, you have merge conflicts to solve. Sorry bout that! 👨‍👩‍👧‍👦

File: packages/react-cosmos-voyager/src/__tests__/index.js (hunk 2 above)
Comment (RadValentin) [inline packages/react-cosmos-voyager/src/__tests__/index.js]: Unfortunately what ends up happening is that `path.join` will try to use OS specific slashes so it will use backslashes for Windows but we're testing against paths that were processed via glob which [insists on forward slashes](https://github.com/isaacs/node-glob#windows). That's why I'm running everything through `slash`

**Comment by RadValentin** [comment]
@skidding @ovidiubute Adressed comments, can you take another look?

**Comment by skidding** [comment]
@reinei can you please try @RadValentin's branch on your machine to make sure the initial issues were corrected. It would help confirm Cosmos works for Windows users. Thanks!

**Comment by reinei** [comment]
```npm install``` is successful on Windows 10 node v7.2.0 npm 3.10.9
and I am able to start the context example without any problems. (If you want, I can see if the changes fixed my initial problems in my own repo as well, but I very much assume thats the case, seeing as I was using a context proxy as well.)

**Comment by skidding** [comment]
@reinei That's good enough, thanks! Let us know if you encounter any other issues in the future.

@RadValentin saved the day!
